name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USERNAME}}
        DOCKER_PSWD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PSWD
        
    - name: Docker build
      run: docker build . --file Dockerfile --tag eddi3as/hosted-runner:latest
      
    - name: Docker push
      run: docker push eddi3as/hosted-runner:latest

  deploy:
    runs-on: self-hosted
    needs: build
    steps:
      - name: Docker login
        env:
          DOCKER_USER: ${{secrets.DOCKER_USERNAME}}
          DOCKER_PSWD: ${{secrets.DOCKER_PASSWORD}}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PSWD

      - name: Pull Docker Image
        run: |
          sudo docker pull eddi3as/hosted-runner:latest

      - name: Run the pulled image (optional)
        run: |
          echo "esc218485" | sudo -S docker run -d --name hosted-runner -p 80:5000 eddi3as/hosted-runner:latest
