name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USERNAME}}
        DOCKER_PSWD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PSWD
        
    - name: Docker build
      run: docker build . --file Dockerfile --tag eddi3as/hosted-runner:$(date +%s)
      
    - name: Docker push
      run: docker push eddi3as/hosted-runner:$(date +%s)
